# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7ba52135139fb5c34666d79ff5a5774ac849d07a6b55fc171834a909b9d4b944fb1f869a0aa0d48c92ce8f6be8d0a0ea13b36966d59e825516b1e41f5a1e7f8

test:
  secret_key_base: 2ea4a13483cab0feed814f51959345f39dc39b9d75e7cf8706cbeaccc472a12a9f38b5b53db102e63ff04d274823f9f79376cdb21f0e8a943a265faed53b0468

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
